apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: todolist-application
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
#      nodePort: 32017